### ISSUE TITLE
The plugin has problems!

### ISSUE THREAD

**Issue by DimaSergeew** [Zrips/BottledExp#33]
1) If a player takes a bottle in his left hand, then he can throw it like a regular bottle with experience, and given that there are external experience modifiers on the server, he can get more experience than he put in infinity
2) If you just write the /bottled store max command, then even if you have 0 levels you will get 1 bottle with experience
3) If you use a dispenser with experience, you will always get more in the case of point 1

**Comment by mrfloris** [comment]
Hi there, can you also include your full output of these commands?
```
ver
ver cmilib
ver bottledexp
```
Thank you for reporting this issue.

**Comment by DimaSergeew** [comment]
> Привет, можете ли вы также включить полный вывод этих команд?
> 
> ```
> ver
> ver cmilib
> ver bottledexp
> ```
> 
> Спасибо, что сообщили об этой проблеме.

![Uploading Screenshot_1.png…]()

**Comment by DimaSergeew** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/75163645/219937271-fb4c91c6-0592-4c11-8fd2-d714f236b5e1.png)
![Screenshot_2](https://user-images.githubusercontent.com/75163645/219937252-446f5fe7-241e-42da-a717-93439eb28075.png)
![Screenshot_3](https://user-images.githubusercontent.com/75163645/219937253-3a9a1fd7-58b5-4279-8ccb-27b615014ae8.png)

**Comment by Zrips** [comment]
1. Should be fixed with next version
2. Should be fixed with next version
3. This cant really do anything with if you have different plugin which modifies dropped exp amounts. What I can do is to introduce minimal exp required for you to be able to store it inside exp bottle to avoid those bottles with tiny amounts of exp inside of them. Next update.
